name: "Online-Kalkulator-Server"
description: "Nginx + PHP + WordPress + MariaDB + phpMyAdmin + Let's Encrypt"
version: "1.0.0"
slug: "online-kalkulator-server"
init: false
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  "8443/tcp": 443
  "8080/tcp": 80
  "8081/tcp": 8081
  "3306/tcp": 3306

webui: "http://[HOST]:[PORT:8080]"

map:
  - "ssl:rw"

options:
  domain: "example.com"
  email: "admin@example.com"
  db_root_password: ""
  db_user_password: ""
  db_user: "wordpress"

schema:
  domain: "str"
  email: "str"
  db_root_password: "str?"
  db_user_password: "str?"
  db_user: "str"
