name: "Online-Kalkulator-Server"
version: "1.0.1"
slug: "online-kalkulator-server"
description: "Nginx + PHP + WordPress + MariaDB + phpMyAdmin + Let's Encrypt"
startup: "services"
boot: "auto"

ports:
  "8080/tcp": 80
  "8443/tcp": 8444
  "8081/tcp": 8081
  "3306/tcp": 3306

webui: "http://[HOST]:[PORT:8080]"

map:
  - "ssl:rw"

options:
  domain: "example.com"
  email: "admin@example.com"
  db_root_password: ""
  db_user_password: ""
  db_user: "wordpress"

schema:
  domain: "str"
  email: "str"
  db_root_password: "str?"
  db_user_password: "str?"
  db_user: "str"
