name: "Online-Kalkulator Addon"
description: "REST-API backend for online-kalkulator"
version: "1.0.1"
slug: "online-kalkulator-addon"
init: false
ports:
  8000/tcp: 8000
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386