name: "Online-Kalkulator Addon"
description: "REST-API backend for online-kalkulator - excel pdf"
version: "1.0.0"
slug: "online-kalkulator-printaddon"
init: false
ports:
  8000/tcp: 8000
webui: "http://[HOST]:[PORT:8000]"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true